In [3]:
import requests
import pandas as pd


key = '인증키'
targetDt = '20220901'

url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={}&targetDt={}'.format(key, targetDt)

response = requests.get(url)
r_data =	 response.json()
r_data

dailyBoxOfficeList = pd.DataFrame(r_data['boxOfficeResult']['dailyBoxOfficeList'])  
dailyBoxOfficeList

dailyBoxOfficeList.columns
dailyBoxOfficeList.head(2)
dailyBoxOfficeList = dailyBoxOfficeList[['movieNm','openDt','rank','audiCnt','audiAcc','scrnCnt','showCnt']]
dailyBoxOfficeList

dailyBoxOfficeList.index=dailyBoxOfficeList.index+1
dailyBoxOfficeList

dailyBoxOfficeList.rename(columns={'movieNm':'영화제목','openDt':'개봉일','rank':'당일 순위',
'audiCnt':'해당일 관객수','audiAcc':'누적관객수','scrnCnt':'해당일 상영 스크린수','showCnt':'해당일 상영 횟수'},inplace=True)

dailyBoxOfficeList

                영화제목         개봉일 당일 순위 해당일 관객수    누적관객수 해당일 상영 스크린수 해당일 상영 횟수
1          육사오(6/45)  2022-08-24     1   47653   727790        1185      4706
2                 헌트  2022-08-10     2   31694  3913122        1134      4214
3          한산: 용의 출현  2022-07-27     3   11230  7082662         660      1907
4                리미트  2022-08-31     4    8041    31466         618      2138
5            탑건: 매버릭  2022-06-22     5    7489  8011838         379       803
6                  놉  2022-08-17     6    3094   377349         279       449
7    명탐정 코난: 할로윈의 신부  2022-07-13     7    1833   465249          29        76
8             불릿 트레인  2022-08-24     8    1743   127918         322       468
9       시맨틱 에러: 더 무비  2022-08-31     9    1656    19624          51        94
10  사랑할 땐 누구나 최악이 된다  2022-08-25    10    1284    16989          69        99